### Application Information ###
name: "logistic_function" # Name of the application from the CSV
description: "Logistic function implementation using CKKS scheme" # Description of the application
title: "logistic_function" # Title to be used in the plot
event_type: "Time" # Event type being esimated

### CSV Paths ###
primitive_benchmarks: "datasets/amd/primitives/all-primitives-timing-results.csv" # Path to the primitive benchmarks CSV
actual_benchmarks: "datasets/amd/microbenchmarks/microbenchmark-results.csv" # Path to the actual application CSV for model validation (optional)

### Performance Model Parameters ###
parameters:
  security_standard_level: none
  n: 16
  depth: 10
  num_threads: sweep

### Application Homomorphic Operation Counts ###
operation_counts:
  CKKS_Add: 70
  CKKS_Sub: 85
  CKKS_Sub_Scalar: 31
  CKKS_Mult_Scalar: 67
  CKKS_Mult: 116
  CKKS_Square: 8
  CKKS_Chebyshev_Series: 1 

### Statistical Methods ###
statistic: "median" # Options: median, mean