### Application Information ###
name: "low_memory_resnet20" # Name of the application from the CSV
description: "Low memory resnet20 inference implementation using CKKS scheme" # Description of the application
title: "resnet" # Title to be used in the plot
event_type: "Time" # Event type being esimated

### CSV Paths ###
primitive_benchmarks: "datasets/amd/primitives/resnet-logreg-primitives.csv" # Path to the primitive benchmarks CSV
actual_benchmarks: "datasets/amd/workloads/resnet-threads-sweep.csv" # Path to the actual application CSV for model validation (optional)

### Performance Model Parameters ###
parameters:
  security_standard_level: none
  n: 16
  depth: 10
  num_threads: sweep

### Application Homomorphic Operation Counts ###
operation_counts:
  CKKS_Add: 6845
  CKKS_Add_Plaintext: 24
  CKKS_Mult_Plaintext: 6475
  CKKS_Bootstrap: 21
  CKKS_Chebyshev_Function: 12
  CKKS_Fast_Rotate_Precompute: 19
  CKKS_Rotate: 1218
  CKKS_Fast_Rotate: 152

### Statistical Methods ###
statistic: "median" # Options: median, mean